public enum EffectsType
{
	HP_BOOTH = 0,
	ATTACK_BOOTH = 1,
	SPEED_BOOTH = 2,
	REVIVAL_BOOTH = 3,
	CALL_BOOTH = 4,
	DAMAGE_BOOTH = 5,
	DAMAGE_REDUCE = 6,
	HP_RECOVERY = 7,
	SPEED_BOOTH_WHEN_GOT_HIT = 8,
	ATTACK_BOOTH_WHEN_SECURE_FLAG = 9,
	EFFECT_COUNT = 10
}
