public enum ItemID
{
	HP_MINOR = 81,
	HP_SMALL = 82,
	HP_MEDIUM = 83,
	HP_GREAT = 84,
	HP_FULL = 85,
	REVIVAL_SMALL = 86,
	REVIVAL_BIG = 87,
	ASSIST_BOOSTER = 88,
	ASSIST_FORCE_SHIELD = 89,
	ASSIST_HYPER_CLIP = 90,
	HP_GIANT = 91
}
